# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('goods_price', models.IntegerField(verbose_name='商品价格')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='生产日期')),
            ],
            options={
                'verbose_name': ('商品类',),
                'db_table': '商品列表',
            },
        ),
    ]
